import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.logo}>
          <Image src="/squirrel-logo.png" alt="Squirrel Logo" width={72} height={27} />
          <p>SQUIRREL ADMIN</p>
        </div>
        <div className={styles.login}>
          <p>Login with Google</p>
          <Image className={styles.google} src="/btn-google.png" alt="Button Google" width={191} height={46} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href=""
          rel="noopener noreferrer"
        >
          &copy; 2022 Squirrel, LLC
        </a>
      </footer>
    </div>
  )
}

export default Home
